import Head from 'next/head';
import { useEffect, useState } from 'react';
import styles from '@/styles/Home.module.css';
import axios from 'axios';

export default function Home() {
  const [data, setData] = useState(null);

  useEffect(() => {
    const options = {
      method: 'GET',
      url: 'https://weatherapi-com.p.rapidapi.com/current.json',
      params: { q: 'Miami' },
      headers: {
        'X-RapidAPI-Key': process.env.API_KEY,
        'X-RapidAPI-Host': process.env.API_HOST,
      },
    };


    axios
      .request(options)
      .then(function (response) {
        setData(response.data);
      })
      .catch(function (error) {
        console.error(error);
      });
  }, []);

  return (
    <>
      <Head>
        <title>Weather App Miami</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main className={styles.main}>
        {data && data.current && (
          <div key={data.current.last_updated_epoch}>
            <h2 className={styles.htitle}>{data.location.name}</h2>
            <p className={styles.text}>
              Feels like: {data.current.feelslike_f}°F right now
            </p>
            <p className={styles.text}>{data.current.condition.text}</p>
          </div>
        )}
      </main>
    </>
  );
}